spring:
  datasource:
    url: jdbc:mysql://localhost:3306/queenkho_db?useSSL=false
    username: root
    password: password_cua_ban
  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo bảng từ Entity trong quá trình dev
    show-sql: true
server:
  port: 8080 # Backend chạy cổng 8080
