/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f9f9ff",
        "on-background": "#141b2b",
        "on-primary-fixed-variant": "#1d4973",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-container": "#0b3d66",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container": "#e9edff",
        "surface-bright": "#f9f9ff",
        "secondary": "#0051d5",
        "inverse-on-surface": "#edf0ff",
        "secondary-fixed": "#dbe1ff",
        "on-primary-container": "#81a8d7",
        "on-surface-variant": "#42474e",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary": "#002746",
        "inverse-primary": "#a2cafa",
        "surface-variant": "#dce2f7",
        "on-tertiary-fixed-variant": "#005236",
        "surface-dim": "#d3daef",
        "primary-fixed": "#d1e4ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#293040",
        "on-tertiary-container": "#17bb83",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-low": "#f1f3ff",
        "surface": "#f9f9ff",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary-container": "#00442d",
        "outline-variant": "#c2c7cf",
        "on-surface": "#141b2b",
        "primary-fixed-dim": "#a2cafa",
        "outline": "#73777f",
        "surface-tint": "#38618c",
        "secondary-container": "#316bf3",
        "on-secondary-fixed": "#00174b",
        "on-secondary-container": "#fefcff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001d36",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dce2f7",
        "on-tertiary-fixed": "#002113",
        "tertiary": "#002c1b",
        "surface-container-high": "#e1e8fd",
        "brand": "#002746",
        "action": "#0051d5",
        "page": "#f9f9ff",
        "ink": "#141b2b",
        "success": "#17bb83",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "2rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "margin": "2rem",
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "code-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "title-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}