version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "12345678@Password"
    ports:
      - "1434:1433"
    
  backend:
    build: ./backend/api
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=sa
      - DB_PASSWORD=12345678@Password
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=QueenKhoDB;encrypt=true;trustServerCertificate=true;
      - VNPAY_TMN_CODE=83NI8FOK
      - VNPAY_HASH_SECRET=YFFJDENNWNIZZYNWLPCRWZFNIKCGEYDQ
      - VNPAY_LOCAL_RETURN_CONFIRM=true
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
