USE QueenKhoDB;
GO

ALTER TABLE activity_logs
ALTER COLUMN action NVARCHAR(500) NOT NULL;

GO

-- Kiểm tra lại sau khi sửa
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'activity_logs' AND COLUMN_NAME = 'action';